### ISSUE TITLE
Allow more parameters to configure MongoDB backend

### ISSUE THREAD

**Issue by coudot** [guimard/apache-session-mongodb#1]
See issue https://jira.ow2.org/browse/LEMONLDAP-984 concerning LemonLDAP::NG MongoDB configuration backend. We should allow the same parameters in MongoDB session backend.

**Comment by coudot** [comment]
Just to be sure: I added the 'host' parameter, it was not there before, is it a mistake?

I also see that these parameters are defined in sub _col in lib/Apache/Session/MongoDB.pm, should we also update this code?

**Comment by guimard** [comment]
It was a mistake I think.

**Comment by coudot** [comment]
Ok for the 'host' parameter, what about the _col subroutine in lib/Apache/Session/MongoDB.pm?

**Comment by guimard** [comment]
Done in V0.16
